require 'open-uri'
require 'rake/clean'

desc 'Run all code and generate PDF report'
task :default => 'doc/report.pdf'

directory 'lib'
CLEAN.include 'lib'

file 'lib/Jama.jar' => 'lib' do |t|
  open(t.name, 'wb') do |f|
    f << open('http://math.nist.gov/javanumerics/jama/Jama-1.0.3.jar').read
  end
end

task :depends => ['lib/Jama.jar']

directory 'build'
CLEAN.include 'build'

task :compile => [:depends, 'build'] do
  sh 'javac -cp "lib/*" -d build src/nz/ac/auckland/cs369/assignment1/*.java'
end

directory 'out'
CLEAN.include 'out'

desc 'Create problem 1 files'
task :problem1 => [:compile, 'out'] do
  Dir.chdir('out') do
    sh 'java -cp "../build:../lib/*" nz.ac.auckland.cs369.assignment1.Problem1 ../data/arman.pgm'
  end
end

desc 'Create problem 2 files'
task :problem2 => [:compile, 'out'] do
  Dir.chdir('out') do
    sh 'java -cp "../build:../lib/*" nz.ac.auckland.cs369.assignment1.Problem2 ../data/arman.pgm'
  end
end

desc 'Create problem 3 files'
task :problem3 => [:compile, 'out'] do
  Dir.chdir('out') do
    sh 'java -cp "../build:../lib/*" nz.ac.auckland.cs369.assignment1.Problem3 ../data/snps.txt 100 2734'
    Dir.chdir('PCA') do
      sh 'Rscript ../../scripts/readandplot.R'
    end
  end
end

desc 'Create problem 4 files'
task :problem4 => [:compile, 'out'] do
  Dir.chdir('out') do
    sh 'java -cp "../build:../lib/*" nz.ac.auckland.cs369.assignment1.Problem4'
  end
end

task :convert do
  FileList.new('**/*.pgm').to_a.zip(FileList.new('**/*.pgm').ext('png')).each do |pgm, png|
    sh "convert #{pgm} #{png}"
  end
end

directory 'doc'

file 'doc/report.pdf' => [:problem1, :problem2, :problem3, :problem4, :convert, 'doc'] do |t|
  Dir.chdir('out') do
    sh "pandoc -V geometry:margin=2cm ../README.md -o ../#{t.name}"
  end
end
CLOBBER.include 'doc'
