require 'open-uri'

directory 'lib'

file 'lib/Jama.jar' => 'lib' do |t|
  open(t.name, 'wb') do |f|
    f << open('http://math.nist.gov/javanumerics/jama/Jama-1.0.3.jar').read
  end
end

file 'lib/jblas.jar' => 'lib' do |t|
  open(t.name, 'wb') do |f|
    f << open('http://central.maven.org/maven2/org/jblas/jblas/1.2.3/jblas-1.2.3.jar').read
  end
end

directory 'build'

task :compile => 'build' do
  sh "javac -cp lib/Jama.jar -d build src/nz/ac/auckland/cs369/assignment1/*.java"
end
