require 'open-uri'

directory 'lib'

file 'lib/Jama.jar' => 'lib' do |t|
  open(t.name, 'wb') do |f|
    f << open('http://math.nist.gov/javanumerics/jama/Jama-1.0.3.jar').read
  end
end

file 'lib/jblas.jar' => 'lib' do |t|
  open(t.name, 'wb') do |f|
    f << open('http://central.maven.org/maven2/org/jblas/jblas/1.2.3/jblas-1.2.3.jar').read
  end
end

task :depends => ['lib/Jama.jar', 'lib/jblas.jar']

directory 'build'

task :compile => ['build', :depends] do
  sh 'javac -cp "lib/*" -d build src/nz/ac/auckland/cs369/assignment1/*.java'
end

directory 'out'

task :problem1 => ['out', :compile] do
  Dir.chdir('out') do
    sh 'java -cp "../build:../lib/*" nz.ac.auckland.cs369.assignment1.Problem1 ../data/arman.pgm'
  end
end
