require 'rake/clean'

CLOBBER.include '*.pdf'

desc 'Generate the report'
task :default => 'report.pdf'

rule '.pdf' => '.ipynb' do |t|
  sh "ipython nbconvert #{t.source} --ExecutePreprocessor.enabled=True --to pdf --template template.tplx"
end
